# Generated by Django 5.1.1 on 2024-11-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_tag_category_product_category_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='tags',
        ),
    ]
